# Generated by Django 5.1 on 2024-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0010_alter_orders_operable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='make',
            field=models.CharField(help_text='Select the car make (company)', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='model',
            field=models.CharField(help_text='Select the car model', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='year',
            field=models.CharField(help_text='Select the car year', max_length=255),
        ),
    ]
