# Generated by Django 5.1 on 2024-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohoulex', '0011_alter_orders_make_alter_orders_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
